apiVersion: v2
name: zigflow
description: Build Temporal workflows from YAML
type: application
version: 0.0.0
icon: https://images.ctfassets.net/0uuz8ydxyd9p/2W8B7bcLSPX9YaSwkfrhmv/eade3fc61520b8cee84cf8605dce3056/Temporal_Symbol_dark_1_2x.png
